name: cosmetics_app
description: Aimira's Cosmetics Advisor

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.2.1
  image_picker: ^1.0.7
  path: ^1.8.0
  http_parser: ^4.0.2
  mime: ^1.0.5
  fluttertoast: ^8.2.4
  provider: ^6.1.1
  http: ^1.1.0
  flutter_svg: ^2.0.7
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  dropdown_button2: ^2.3.9
  multi_dropdown: ^2.1.4
  cupertino_icons: ^1.0.2
  salomon_bottom_bar: ^3.3.2
  logger: ^2.1.0
  story_view: ^0.16.5
  dashed_circle: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/assets/loginScreenLogo.svg
    - lib/assets/womanLogo.svg
    - lib/assets/mainBanner.png
    - lib/assets/avatarPlaceholder.png
    - .env

  uses-material-design: true

